[window]
opacity = 1

[font]
size = 13.25

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 350
blink_timeout = 5

[colors]
cursor = {text = "#FFFFFF", cursor = "#1e90ff"}
footer_bar = { foreground = "#ED0800", background = "#FFFFFF"}

[colors.primary]
background = "#000000"

